/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  prefix: 'tw-',
  theme: {
    extend: {
      fontFamily: {
        inter: ['Inter', 'Roboto', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
        sans: ['Inter', 'Roboto', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
      },
      colors: {
        brand: {
          DEFAULT: '#1ED74B',
          dark: '#19B23E',
          hover: '#19B23E',
          active: '#19B23E',
          light: '#D4F5DC',
          soft: '#D4F5DC',
          muted: '#D4F5DC',
          disabled: '#D4F5DC',
        },
        surface: {
          page: '#F8F8F8',
          app: '#F8F8F8',
          card: '#FFFFFF',
          white: '#FFFFFF',
          muted: '#F8F8F8',
          raised: '#FFFFFF',
          overlay: 'rgb(20 22 20 / 48%)',
          inverse: '#262626',
        },
        text: {
          primary: '#262626',
          heading: '#111010',
          secondary: '#545454',
          muted: '#95939F',
          icon: '#95939F',
          neutral: '#737373',
          disabled: '#95939F',
          inverse: '#FFFFFF',
          brand: '#19B23E',
          danger: '#E5484D',
        },
        border: {
          DEFAULT: '#95939F',
          subtle: '#95939F',
          strong: '#545454',
          focus: '#1ED74B',
          error: '#E5484D',
        },
        state: {
          success: '#1ED74B',
          'success-soft': '#D4F5DC',
          warning: '#F2C94C',
          'warning-soft': '#FFF8DA',
          error: '#E5484D',
          'error-soft': '#FDECEC',
          info: '#2F80ED',
          'info-soft': '#EAF3FF',
        },
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        control: '10px',
        card: '12px',
        sheet: '16px',
        pill: '999px',
      },
      boxShadow: {
        control: '0 1px 2px rgb(24 29 24 / 8%)',
        card: '0 8px 24px rgb(24 29 24 / 8%)',
        sheet: '0 -12px 32px rgb(24 29 24 / 14%)',
        overlay: '0 16px 48px rgb(24 29 24 / 18%)',
      },
      fontSize: {
        h1: ['20px', { lineHeight: '26px', letterSpacing: '0', fontWeight: '600' }],
        h2: ['18px', { lineHeight: '23.4px', letterSpacing: '0', fontWeight: '600' }],
        h3: ['16px', { lineHeight: '20.8px', letterSpacing: '0', fontWeight: '500' }],
        t1: ['16px', { lineHeight: '20.8px', letterSpacing: '0', fontWeight: '400' }],
        t2: ['14px', { lineHeight: '18.2px', letterSpacing: '0', fontWeight: '400' }],
        t3: ['12px', { lineHeight: '15.6px', letterSpacing: '0', fontWeight: '400' }],
        button: ['16px', { lineHeight: '20.8px', letterSpacing: '0', fontWeight: '600' }],
      },
      spacing: {
        'safe-bottom': 'env(safe-area-inset-bottom)',
        touch: '44px',
        control: '48px',
        nav: '64px',
        sheet: '24px',
      },
      zIndex: {
        sheet: '700',
        overlay: '690',
        toast: '900',
      },
    },
  },
  plugins: [],
}
